[package]
name = "simple-warp-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
warp = { version = "0.3", features = ["tls"] }
